
on: [push]
#on:
#  release:
#    types: [published]

jobs:
  build_and_push_docker:
    runs-on: ubuntu-latest
    name: Build Dockerfile and push to Dockerhub
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Timbermill Server
        run: mvn -DskipTests timbermill-java/timbermill-server/pom.xml
      - name: Build Docker
        uses: ./timbermill-java/timbermill-server/ # Uses an action in a specific path
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./timbermill-java/timbermill-server/
          push: true
#          tags: edengaldocker/timbermill-open-source:latest
          tags: ozafar2021/test:latest

